### ISSUE TITLE
Numéro de ligne peut être supérieur à 10 !

### ISSUE THREAD

**Issue by fvannel** [claudiosousa/HepiaBlocks#3]
Autorise t'on des valeurs en dehors de la zone d'affichage ?

**Comment by fvannel** [comment]
Dans la fonction "allumer ligne"

**Comment by claudiosousa** [comment]
On l'autorise car on permet l'utilisation de variables.

Pour y remédier, nous avons maintenant un nouveau block qui permet de limiter la valeur d'une variable:
![image](https://user-images.githubusercontent.com/776240/48983805-c9e8da80-f0f3-11e8-8c45-bdb3182668c8.png)

Le code python généré est:

![image](https://user-images.githubusercontent.com/776240/48983812-f56bc500-f0f3-11e8-8f91-8631fcc0cba2.png)
